// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-09-12 17:36:06.439853624 +0800 CST m=+0.069475984

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "这是API说明文档，开发服务器才有， 正式部署之后没有。  认证时候填 token eyJhbGciOiJIU...(注意token后面有个空格， token向管理员申请)",
        "title": "API说明",
        "termsOfService": "http://9200.gpu.raidcdn.cn:9700",
        "contact": {
            "name": "API Support",
            "url": "http://9200.gpu.raidcdn.cn:9700",
            "email": "ggxxde@163.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://9200.gpu.raidcdn.cn:9700"
        },
        "version": "1.0"
    },
    "host": "9200.gpu.raidcdn.cn:9700",
    "basePath": "/",
    "paths": {
        "/api1/authping": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "ping检查网络是否正常，需要登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 连通性（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/batchinfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得所有批次信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 数据/项目（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/categoryinfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得细胞分类信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 数据/项目（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/createdataset": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "新建数据/项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 数据/项目（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/dtinfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得所有图片及标注的统计信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 数据/项目（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/getimgnptypebymids": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过所选中的批次/病例/图片, 返回N/P图片的个数统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 数据/项目（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/imglistsofwanted": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得所选批/次病/细胞类型的图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 数据/项目（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/imglistsonebyone": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过图片的ID获得对应的所有标注信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 数据/项目（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/job": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "python端请求一个任务（数据处理/训练/预测），python端会指定请求任务的状态和类型",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 任务（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"data\": \"cookie token is empty\", \"status\": 63}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/joblog": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得任务数据处理/训练/预测后端产生的log",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 任务（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/jobmodel": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得训练任务生成模型的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 模型（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/jobpercent": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得任务进度（数据处理/训练/预测）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 任务（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/jobresult": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得任务状态（数据处理/训练/预测）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 任务（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "python端更新任务状态/进度（数据处理/训练/预测）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 任务（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/listdatasets": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "按数据库存储顺序依次获得数据/项目信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 数据/项目（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/medicalidinfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得所有病例信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 数据/项目（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/ping": {
            "get": {
                "description": "ping检查网络是否正常",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 连通性（不需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/savemodel": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "把训练任务生成模型信息存数据库",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 模型（需要认证）"
                ],
                "responses": {
                    "200": {
                        "description": "{\"ping\": \"pong\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api1/userinfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得当前用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 用户"
                ],
                "summary": "用户信息",
                "responses": {
                    "200": {
                        "description": "{\"data\": \"ok\",\t\"status\": 200}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "用户通过邮箱/用户名/手机号登录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 用户"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录信息表单",
                        "name": "Login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "expire\": \"当前token到期时间\", \"status\": 200, \"token\": \"token的字符串\",\"user\": {\"id\": 3,\"mobile\": \"string\",\"email\": \"string\",\"name\": \"string\",\"image\": \"http://workaiossqn.tiegushi.com/xdedu/images/touxiang.jpg\",\"type_id\": 1000,\"created_at\": \"2019-09-12T10:05:39Z\",\"updated_at\": \"2019-09-12T03:34:17Z\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "description": "已经登录用户注销",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 用户"
                ],
                "summary": "已经登录用户注销",
                "responses": {
                    "200": {
                        "description": "status\": 200, \"data\": \"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "注册新用户",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API1 用户"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "description": "注册信息表单",
                        "name": "Register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": \"User already exist\",\t\"status\": 70}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.login": {
            "type": "object",
            "required": [
                "mobile",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "string",
                    "example": "youremail@163.com 正确的邮箱格式"
                },
                "mobile": {
                    "type": "string",
                    "format": "string",
                    "example": "手机号码"
                },
                "password": {
                    "type": "string",
                    "format": "string",
                    "example": "用户密码"
                },
                "username": {
                    "type": "string",
                    "format": "string",
                    "example": "用户名，英文数字组成"
                }
            }
        },
        "controllers.register": {
            "type": "object",
            "required": [
                "confirmPassword",
                "mobile",
                "password"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string",
                    "format": "string",
                    "example": "确认密码"
                },
                "email": {
                    "type": "string",
                    "format": "string",
                    "example": "youremail@163.com 正确的邮箱格式"
                },
                "mobile": {
                    "type": "string",
                    "format": "string",
                    "example": "手机号码"
                },
                "password": {
                    "type": "string",
                    "format": "string",
                    "example": "设置密码"
                },
                "username": {
                    "type": "string",
                    "format": "string",
                    "example": "用户名，英文数字组成"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{ Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface {}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
